#!/bin/sh
#20231227 script created.
#20240108 core2 -> nocona

#***SET THESE***
BUILDSPATH='/mnt/build/builds/oe/scarthgap'
QFOLDER='oe-quirky'

MNTPT="$(realpath "$0" | cut -f 1,2,3 -d '/')"
if [ "$MNTPT" != "/mnt/build" ];then
 grep -q '/mnt/build ' /proc/mounts
 if [ $? -eq 0 ];then
  echo "Error, /mnt/build is mounted, but you need to open a terminal under /mnt/build"
 else
  echo "Error, partition must be mounted on /mnt/build. run 'bind-mnt-on-mnt-build' first."
 fi
 exit
fi

if [ ! -d $BUILDSPATH ];then
 echo "Error, folder ${BUILDSPATH} does not exist."
 exit
fi

if [ "$(whoami)" != "root" ];then
 echo "Error, must run this script as root user."
 exit
fi

#allow ${QFOLDER} to pre-exist
if [ -d ${BUILDSPATH}/${QFOLDER} ];then
 echo "${BUILDSPATH}/${QFOLDER} already exists, updating..."
 for A in `find ${BUILDSPATH}/${QFOLDER} -mindepth 1 -maxdepth 1 -type d -not -name 'build-*' | tr '\n' ' '`
 do
  rm -rf ${A}
 done
 sync
 for A in `find ${BUILDSPATH}/${QFOLDER} -mindepth 1 -maxdepth 1 -type f -or -type l | tr '\n' ' '`
 do
  rm -f ${A}
 done
 sync
fi

PROJECTPATH="$(pwd)"

mkdir -p ${BUILDSPATH}/${QFOLDER}
mkdir -p ${BUILDSPATH}/downloads

echo "Populating ${BUILDSPATH}/${QFOLDER}..."
tar -xf downloads-oe/openembedded-core.tar.gz --directory=${BUILDSPATH}/${QFOLDER} --strip=1
grep -q scarthgap ${BUILDSPATH}/${QFOLDER}/meta/conf/layer.conf
if [ $? -ne 0 ];then
 sed -i -e 's%nanbield%nanbield scarthgap%' ${BUILDSPATH}/${QFOLDER}/meta/conf/layer.conf
fi
tar -xf downloads-oe/meta-openembedded.tar.gz --directory=${BUILDSPATH}/${QFOLDER} --strip=1
tar -xf downloads-oe/bitbake.tar.gz --directory=${BUILDSPATH}/${QFOLDER}
tar -xf downloads-oe/meta-yocto.tar.gz --directory=${BUILDSPATH}/${QFOLDER} --strip=1
sync

tar -xf downloads-oe/meta-office.tar.gz --directory=${BUILDSPATH}/${QFOLDER}

tar -xf downloads-oe/meta-qt5.tar.gz --directory=${BUILDSPATH}/${QFOLDER}
#20211217 attempting build, maybe this not needed:
sed -i -e 's%{OE_QMAKE_CXXFLAGS}%{OE_QMAKE_CXXFLAGS} -fpermissive%' ${BUILDSPATH}/${QFOLDER}/meta-qt5/classes/qmake5_base.bbclass
sed -i -e 's%{CXXFLAGS}%{CXXFLAGS} -fpermissive%' ${BUILDSPATH}/${QFOLDER}/meta-qt5/classes/qmake5_base.bbclass
sync

#tar -xf downloads-oe/meta-conan.tar.gz --directory=${BUILDSPATH}/${QFOLDER}
tar -xf downloads-oe/meta-clang.tar.gz --directory=${BUILDSPATH}/${QFOLDER}
tar -xf downloads-oe/meta-chromium.tar.gz --directory=${BUILDSPATH}/${QFOLDER} --strip=1

#rust... 20231230 remove...
#sed -i -e 's/^RUSTVERSION .*/RUSTVERSION ?= "1.73.0"/' ${BUILDSPATH}/${QFOLDER}/meta/conf/distro/include/tcmode-default.inc
#tar -xf downloads-oe/meta-rust.tar.gz --directory=${BUILDSPATH}/${QFOLDER}
#grep -q scarthgap ${BUILDSPATH}/${QFOLDER}/meta-rust/conf/layer.conf
#if [ $? -ne 0 ];then
# sed -i -e 's%mickledore%mickledore scarthgap%' ${BUILDSPATH}/${QFOLDER}/meta-rust/conf/layer.conf
#fi

#customization for quirky/easyos...
cp -a -f --remove-destination quirky/* ${BUILDSPATH}/${QFOLDER}/
sync

#for musl build...
cp -a ${BUILDSPATH}/${QFOLDER}/meta-quirky ${BUILDSPATH}/${QFOLDER}/meta-quirky-cut
for aCUT in recipes-browser/chromium recipes-browser/firefox recipes-devtools/archive-zip recipes-devtools/clang recipes-gnome/evince recipes-gnome/gthumb recipes-gnome/gtk4 recipes-gnome/nautilus recipes-gnome/tracker recipes-graphics/harfbuzz recipes-graphics/mesa recipes-graphics/scribus recipes-libreoffice/libreoffice recipes-multimedia/sox recipes-multimedia/vlc recipes-multimedia/x265 recipes-qt/qt5 recipes-quirky/freetype-static recipes-quirky/gui-engine recipes-quirky/libsdl-fb recipes-quirky/obs recipes-quirky/vym recipes-support/mlt recipes-support/redland recipes-quirky/keepassxc recipes-multimedia/shotcut recipes-quirky/symphytum recipes-quirky/aqemu recipes-quirky/qtemu recipes-quirky/qlipper
do
 if [ -d "${BUILDSPATH}/${QFOLDER}/meta-quirky-cut/${aCUT}" ];then
  rm -rf ${BUILDSPATH}/${QFOLDER}/meta-quirky-cut/${aCUT}
 fi
done

# copy the docs also...
cp -a docs ${BUILDSPATH}/${QFOLDER}/
sync

###hacks###
#allow run as root...
sed -i -e 's%if 0 == os\.getuid%if 9999 == os.getuid%' ${BUILDSPATH}/${QFOLDER}/meta/classes-global/sanity.bbclass

#kill the msg "... has not been validated with this version ..."
Wstr="bb.warn('Host distribution \"%s\""
sed -i -e "s/${Wstr}/#${Wstr}/" ${BUILDSPATH}/${QFOLDER}/meta/classes-global/sanity.bbclass

#replace "core2" with "nocona"...
sed -i -e 's%^DEFAULTTUNE .*%DEFAULTTUNE = "nocona-64"%' ${BUILDSPATH}/${QFOLDER}/meta-yocto-bsp/conf/machine/genericx86-64.conf
sed -i -e 's%tune\-core2%tune-nocona%' ${BUILDSPATH}/${QFOLDER}/meta-yocto-bsp/conf/machine/genericx86-64.conf
sed -i -e 's%^DEFAULTTUNE .*%DEFAULTTUNE = "i686"%' ${BUILDSPATH}/${QFOLDER}/meta-yocto-bsp/conf/machine/genericx86.conf
sed -i -e 's%tune\-core2%tune-i686%' ${BUILDSPATH}/${QFOLDER}/meta-yocto-bsp/conf/machine/genericx86.conf

#181202 to compile ghostscript with libgs, need this...
#ref: https://patchwork.openembedded.org/patch/137913/
echo '
SECURITY_CFLAGS_pn-ghostscript = "${SECURITY_NO_PIE_CFLAGS}"' >> ${BUILDSPATH}/${QFOLDER}/meta/conf/distro/include/security_flags.inc
#see also ${BUILDSPATH}/${QFOLDER}/meta-quirky/recipes-extended/ghostscript/ghostscript_9.20.bbappend

#install 'shadow' pkg fails...
grep -H 'chown root:mail' ${BUILDSPATH}/${QFOLDER}/meta/recipes-extended/shadow/shadow.inc > ${BUILDSPATH}/chown-hacks.log
sed -i -e 's%chown root:mail%#chown root:mail%' ${BUILDSPATH}/${QFOLDER}/meta/recipes-extended/shadow/shadow.inc
# do_package 'dbus' pkg fails...
DBUSBB="$(find ${BUILDSPATH}/${QFOLDER}/meta/recipes-core/dbus -mindepth 1 -maxdepth 1 -type f -name 'dbus_1.*.bb')"
#ex: sed -i -e 's%chown %#chown %' ${BUILDSPATH}/${QFOLDER}/meta/recipes-core/dbus/dbus_1.14.0.bb
grep -H 'chown ' ${DBUSBB} >> ${BUILDSPATH}/chown-hacks.log
sed -i -e 's%chown %#chown %' ${DBUSBB}
#more...
for aBB in sysvinit
do
 xaBB="$(find ${BUILDSPATH}/${QFOLDER}/meta/*/${aBB} -mindepth 1 -maxdepth 1 -type f -name "${aBB}_*.bb")"
 if [ "$xaBB" ];then
  grep -H 'chown ' ${xaBB} >> ${BUILDSPATH}/chown-hacks.log
  sed -i -e 's%chown %#chown %' ${xaBB}
 fi
done
for aBB in polkit geoclue
do
 xaBB="$(find ${BUILDSPATH}/${QFOLDER}/meta-oe/*/${aBB} -mindepth 1 -maxdepth 1 -type f -name "${aBB}_*.bb")"
 if [ "$xaBB" ];then
  grep -H 'chown ' ${xaBB} >> ${BUILDSPATH}/chown-hacks.log
  sed -i -e 's%chown %#chown %' ${xaBB}
 fi
done
for aBB in ntp blueman
do
 xaBB="$(find ${BUILDSPATH}/${QFOLDER}/meta-networking/*/${aBB} -mindepth 1 -maxdepth 1 -type f -name "${aBB}_*.bb")"
 if [ "$xaBB" ];then
  grep -H 'chown ' ${xaBB} >> ${BUILDSPATH}/chown-hacks.log
  sed -i -e 's%chown %#chown %' ${xaBB}
 fi
done

#20221201 libreoffice: clucene-core does not compile, use builtin
sed -i '/clucene-core/d' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice-native.bb
#no, replace with libxinerama, which is required... no, dep done in libreoffice.bbappend
sed -i '/clucene-core/d' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb
#sed -i -e 's%clucene-core%libxinerama%' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb
sed -i -e 's%with-system-clucene%without-system-clucene%' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb
sed -i -e 's%with-system-clucene%without-system-clucene%' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.inc
#pkg postgresql does not compile...
sed -i '/ postgresql /d' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb
#build without gstreamer dep...
sed -i '/gstreamer/d' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb
#have my own recipes for inkscape and scribus...
rm -rf ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-graphics
#hack libreoffice.bb: disable do_install() as replacement in libreoffice.bbappend
cp -a -f ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bbORIG
sed -i -e 's%^do_install%XXXdo_install%' ${BUILDSPATH}/${QFOLDER}/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb

#20240519 hopefully temporary...
sed -i -e 's%nanbield%nanbield scarthgap%' ${BUILDSPATH}/${QFOLDER}/meta-office/conf/layer.conf

#20221201 remove coz have my own .bbappend in meta-quirky/recipes-graphics/harfbuzz...
rm -rf ${BUILDSPATH}/${QFOLDER}/meta-office/appends/harfbuzz

#20221201 annoying hard-coded revision#
#ex: ${BUILDSPATH}/${QFOLDER}/meta/recipes-support/db/db_5.3.28.bb has "r1"
BBFILES="$(find ${BUILDSPATH}/${QFOLDER}/meta* -type f -name '*.bb')"
for aBBF in $BBFILES
do
 [ "$aBBF" == "" ] && continue
 sed -i -e 's%^PR = "r[0-9]%#PR = %' $aBBF
done
sync

#2021 libreoffice downloads extra source packages, have already got them here (for libreoffice 7.1.3.2)
cd $PROJECTPATH
if [ ! -d ${BUILDSPATH}/tarballs-libreoffice ];then
 cd $BUILDSPATH
 wget https://distro.ibiblio.org/easyos/source/extra/oe-qky-kirkstone/tarballs-libreoffice.tar.gz
 tar -xf tarballs-libreoffice.tar.gz
 sync
 rm -f tarballs-libreoffice.tar.gz
 cd ${PROJECTPATH}
fi

#20231229 remove... 
##20221206
##clash between these:
## meta/recipes-devtools/llvm <<provides llvm 13.0.1
## meta-clang/recipes-devtools/clang <<provides llvm 14.0.3
##remove one of them...
#rm -rf ${BUILDSPATH}/${QFOLDER}/meta/recipes-devtools/llvm
##and have created meta-quirky/recipes-devtools/clang/clang_%.bbappend
## to rprovide what llvm did. 20221211 also do this... 20231229...
#CLver1="$(grep '^MAJOR_VER =' ${BUILDSPATH}/${QFOLDER}/meta-clang/recipes-devtools/clang/clang.inc | cut -f 2 -d '"')"
#CLver2="$(grep '^MINOR_VER =' ${BUILDSPATH}/${QFOLDER}/meta-clang/recipes-devtools/clang/clang.inc | cut -f 2 -d '"')"
#CLver3="$(grep '^PATCH_VER =' ${BUILDSPATH}/${QFOLDER}/meta-clang/recipes-devtools/clang/clang.inc | cut -f 2 -d '"')"
#CLANGver="${CLver1}.${CLver2}.${CLver3}" #ex: 17.0.6
#sed -i -e 's/^LLVMVERSION .*/LLVMVERSION ?= "'"${CLANGver}"'"/' ${BUILDSPATH}/${QFOLDER}/meta/conf/distro/include/tcmode-default.inc

#fix absolute paths in bblayers.conf...
PTN1="s%QPATH%${BUILDSPATH}/${QFOLDER}%"
sed -i -e "$PTN1" ${BUILDSPATH}/${QFOLDER}/build-amd64/conf/bblayers.conf
sed -i -e "$PTN1" ${BUILDSPATH}/${QFOLDER}/build-amd64-musl/conf/bblayers.conf




echo "$PROJECTPATH" > ${BUILDSPATH}/${QFOLDER}/PROJECTPATH
sync

sync
echo
echo "Folder '${BUILDSPATH}/${QFOLDER}' populated.
Now what you have to do, is open a terminal in '${QFOLDER}'
and run this, for pc x86_64 nocona build, as the root user:
# source ./oe-init-build-env build-amd64
# bitbake-layers show-layers
# bitbake -g core-image-minimal
# bitbake core-image-minimal
"
###end###
