
#20241001
DEPENDS = "zlib"
EXTRA_OECONF:append = " --without-lzma --without-xen"

do_compile:append() {
 cd ${B}
 ${CC} -static -m64 -march=nocona -mtune=nocona -mno-sse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/recipe-sysroot -L/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/recipe-sysroot/usr/lib  -o kexec/kexec.static kexec/kexec.o kexec/ifdown.o kexec/kexec-elf.o kexec/kexec-elf-exec.o kexec/kexec-elf-core.o kexec/kexec-elf-rel.o kexec/kexec-elf-boot.o kexec/kexec-pe-zboot.o kexec/kexec-iomem.o kexec/firmware_memmap.o kexec/crashdump.o kexec/crashdump-xen.o kexec/phys_arch.o kexec/lzma.o kexec/zlib.o kexec/kexec-xen.o kexec/symbols.o kexec/proc_iomem.o kexec/virt_to_phys.o kexec/phys_to_virt.o kexec/add_segment.o kexec/add_buffer.o kexec/arch_reuse_initrd.o kexec/arch/i386/kexec-elf-x86.o kexec/arch/i386/kexec-bzImage.o kexec/arch/i386/kexec-multiboot-x86.o kexec/arch/i386/kexec-mb2-x86.o kexec/arch/i386/kexec-beoboot-x86.o kexec/arch/i386/kexec-nbi.o kexec/arch/i386/x86-linux-setup.o kexec/arch/i386/kexec-x86-common.o kexec/arch/i386/crashdump-x86.o kexec/arch/x86_64/kexec-x86_64.o kexec/arch/x86_64/kexec-elf-x86_64.o kexec/arch/x86_64/kexec-elf-rel-x86_64.o kexec/arch/x86_64/kexec-bzImage64.o kexec/purgatory.o libutil.a -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/kexec-tools-2.0.28=/usr/src/debug/kexec-tools/2.0.28  -fdebug-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/kexec-tools-2.0.28=/usr/src/debug/kexec-tools/2.0.28  -fmacro-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/build=/usr/src/debug/kexec-tools/2.0.28  -fdebug-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/build=/usr/src/debug/kexec-tools/2.0.28  -fdebug-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/recipe-sysroot=  -fmacro-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/recipe-sysroot=  -fdebug-prefix-map=/mnt/build/builds/oe/scarthgap/oe-quirky/build-amd64-musl/tmp/work/nocona-64-poky-linux-musl/kexec-tools/2.0.28/recipe-sysroot-native=  -fno-strict-aliasing -Wall -Wstrict-prototypes -lz 
}

do_install:append() {
 install ${B}/kexec/kexec.static  ${D}/usr/sbin
}
