#!/bin/sh

rm -f meta-kf5.tar.gz
git clone -b master https://invent.kde.org/packaging/yocto-meta-kf5.git meta-kf5 --depth 1
cd meta-kf5
rm -rf .git
sed -i -e 's%^LAYERSERIES_COMPAT_kf5 = .*%LAYERSERIES_COMPAT_kf5 = "scarthgap"%' conf/layer.conf
sed -i -e 's%^REQUIRED_DISTRO_FEATURES = .*%REQUIRED_DISTRO_FEATURES = "x11"%' recipes-kf5/packagegroups/packagegroup-kde-frameworks5.bb
rm -rf recipes-kf5/obsolete
#weird, cannor change polkit to polkit105 in .bbappend need to do it here...
sed -i -e 's%^DEPENDS = .*%DEPENDS = "qtbase polkit105"%' recipes-kdesupport/polkit-qt-1.inc
cd ..
dir2tgz meta-kf5
rm -rf meta-kf5
sync

